### ISSUE TITLE
Search a Lv2diag.self Version of Your IDPSet for me

### ISSUE THREAD

**Issue by xenocracy** [Zarh/IDPSet#1]
Hello Mr. Zarh
Have an Error 8002F2C4 and can not Install ever OFW,CFW this is the End of my Ps3.
Have set Idps - Console Id from a other Ps3 to my ps3. Now I Reset my Harddisc
And this is the End of the Game. Can go to FSM, Have E3 Nor Flasher.
Have an FSM enabler Stick Tennsy 2.0++.
Have a Original Backup bkpps3.bin. without Patch idps.
Have patched bkpps3.bin for 3.55 ROS1 and ROS2. PS3DumpChecker say OK
Write Your Tool IDPSet_v0.62.pkg the Idps - Console Id only on the Nor Nand
 or to a other Chip in the Playstation 3 ?
Can You make a Lv2diag.self ? I have the idps.bin, psid.bin, eid_root_key.
Thank You and Please give me a Answere to: xenocracy_2001 at yahoo.com

**Comment by Zarh** [comment]
I don't understand ...
